### PR TITLE
Fix: Resolve linting errors

### PR DESCRIPTION
**Pull request by mark-escosura**
## Description

- Fixed ternary syntax error in `InstructorNewsFeed/index.js`
- Added less to format script in `package.json`
- Formatted all files with the format script
- Resolved all compile errors/warnings
- Changed `superAdminSidebar.js`'s anchor elements to react-router links

Fixed the issues with @natecheney-dev @waylonturbes @PriscilaMonteiro @ModupeD @krisf451 

Fixes (Issue #149)

## Loom Video

https://youtu.be/8AKpRb7VHKg

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by natecheney-dev — APPROVED** [review]
Great job finding what caused the error, the linter wasn't making it clear what the issue was.

**Review by mcmillanj — APPROVED** [review]
small bug, good catch, ryan just spoke about this .

**Review by waylonturbes — APPROVED** [review]
Great job finding and fixing this error so quickly. The changes look good.

In the future, I would try to make  branch names more specific, as it is hard to know what changes are being made without looking at the code. Something like `fix/instructor-news-feed-parsing-error` would be preferred.

**Comment by mark-escosura** [comment]
> Great job finding and fixing this error so quickly. The changes look good.
> 
> In the future, I would try to make branch names more specific, as it is hard to know what changes are being made without looking at the code. Something like `fix/instructor-news-feed-parsing-error` would be preferred.

thanks waylon, next time I'll be more specific about naming my branches. Do you know if there's a way to change a branch name via git?

**Comment by waylonturbes** [comment]
> thanks waylon, next time I'll be more specific about naming my branches. Do you know if there's a way to change a branch name via git?
Once you push up a branch, renaming it is not possible (at least not easily). Don't worry about it for this branch, just the future ones.

**Comment by PriscilaMonteiro** [comment]
Great Working getting this bug fixed for us.

**Comment by ModupeD** [comment]
Awesome job finding that error message.

**Review by mcmillanj — APPROVED** [review]
you disabled linting ,very simple fix  and effective, great

**Pull request merged**
