### PR TITLE
BL-737-fe-logout-button-on-header-still-says-logout-even-when-no-one-is-logged-in

### PR DESCRIPTION
**Pull request by Cassius-Cassity**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/844b06c0c82648f695f64a90b2f97eb7

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by AnthonyLayne — APPROVED** [review]
Looks good. Would recommend getting rid of the console.log on line 39. Maybe organizing the imports a bit. (It looks like all of that is from a previous dev) Great job on your code though!

**Review by Irving-Delgad0 — APPROVED** [review]
Looks great! I would recommend changing the condition (role_id <= 5) since it will cause problems if there is ever a 6th role added (unlikely but could happen) Other than that great job!

**Comment by Cassius-Cassity** [comment]
Thank you guys for the feedback!

**Review by vasilii-garanin — APPROVED** [review]
Hi guys, good job fixing this problem. I noticed it every time when I launched my local deployment and it was annoying. Code for logoutRender looks good and from your demonstration it works correctly.

**Review by Roadlyfe — APPROVED** [review]
Looks great! clean code.

**Review by tkordysh — APPROVED** [review]
Thanks for fixing that. It definitely would confuse users otherwise. Well done!

**Review by DawsonReschke — APPROVED** [review]
Well done, code looks clean, I think that it could probably have been implemented inside of the already existing useEffect hook. Nice job though!

**Pull request merged**
