### PR TITLE
BL-466 write and implement unit tests for homepage features

### PR DESCRIPTION
**Pull request by dirkknibbe**
## Description

The ticket was to write at least 3 unit tests on the homepage to make sure the features there were in the proper format. We used a bit of Test Driven Development strategy as there were indeed a few problems with how the data is formatted on the homepage. We wrote a total of 7 tests, 4 of which will run once the data being rendered on the homepage is remade into the proper format. And there are helpful comments next to these tests explaining these in a little more detail. 

Fixes # BL-466-write-and-implement-unit-tests-for-homepage-features

## Loom Video

https://www.loom.com/share/52a8dc1220ca4f05a79ebe0faf0bdedb

## Type of change

- [x] Unit tests created for an existing component.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by kevkenshi-max — APPROVED** [review]
It is essential to have testing for each project before deploying. Nicely done here testing the landing page.

**Review by ShahWahidy — APPROVED** [review]
Great work guys. I watched the loom video and you did a good job of explaining why you guys kept the OktaAuth state null. I liked how you implemented a beforeEach block to keep the code clean and to not run into code redundancy.

**Review by tvolchko — APPROVED** [review]

**Review by ivanovicuros — APPROVED** [review]

**Review by Benroberts37 — APPROVED** [review]
Great job writing tests! And cool explanation in the loom video about test driven development. I remember hearing about that during one of our units, but your video + some research after on Youtube helped me understand it a lot more. Also, the tests look great. Great job.

**Review by Ogden-R — APPROVED** [review]
Great job working around the bug in Okta! that was smart to set it to null while there is an error happening.  very nice  unit tests.

**Review by anastasia-lapteva — APPROVED** [review]
Hello Dirk and Michael,

I am happy to see another PR from you guys, reviewing your work is a pleasure. I like that you chose to practice the test-driven development strategy that we learned at BloomTech. I think your way of getting around the errors with OktaAuth is clever, it makes sense to set authState to null since testing home page does not require any authentication. Good job with your beforeEach() function that renders each component through the router before running tests. Thank you for leaving helpful comments describing why the 4 tests are currently failing (because some data not in correct format). You guys went above and beyond with writing the tests and set the future developers who will continue working on this up for success.

**Review by JamesFincher — APPROVED** [review]
Very slick using the null. Comments are helpful. Good loom presentation by the way.

**Review by jose-mercado — APPROVED** [review]
As we all know, tests are super important and quite frankly some developers least favorite part of programming (mostly speaking for myself hahaha). Very happy to see 7 functional tests written out, I also like the comments explaining why some tests are going to pass and why some won't. amazing job

**Review by leewp8 — APPROVED** [review]
Nice work guys. Test driven development is not exactly the fun part of coding so kudos to you both. It sounds like you ran into a few snags along the way according to your loom video, so nice job working around those as well. Code looks tidy as well.

**Comment by laurensruiz** [comment]
It was a smart how you were able to work around the error with OktaAuth. It was insightful and I kept note of it myself in case I ran into a similar problem in the future.  The unit tests look great and neat as well and I appreciate how they were explained as well.

**Pull request merged**
