### PR TITLE
BL-88 Feature/redux overhaul/newsfeed

### PR DESCRIPTION
**Pull request by anastasia-lapteva**
## Description

BL-88 Redux Overhaul: InstructorNewsFeed Folder

## Summary of changes: 

- Connected `NewsFeedPutModal.js` to redux/back-end. Moved axios call to an action, and ensured that we’re updating our database and local state (redux) at the same time.
- Connected `NewsFeedPostModal.js` to redux/back-end. Moved axios call to an action, and ensured that we’re updating our database and local state (redux) at the same time.
- Connected `NewsContainer.js` to redux/back-end. Moved axios call to an action, and ensured that we're updating our database and local state (redux) at the same time.
- Connected `IndividualNews.js` to redux/back-end. Ensured that we're updating our database and local state (redux) at the same time.
- Connected `Title.js` to redux/back-end. Ensured that we're updating our database and local state (redux) at the same time.
- Connected `index.js` to redux/back-end. Ensured that we're updating our database and local state (redux) at the same time.

Fixes # (issue)

- Connects all components in InstructorNewsFeed Folder to redux.

## Loom Video

https://www.loom.com/share/0c6f66462d644fb8a44c91bdad836d6d

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by dirkknibbe — APPROVED** [review]
Great job using UseDispatch and MapStateToProps! Looks a whole lot cleaner.

**Review by ShahWahidy — APPROVED** [review]
Good work Anastasia. You have got a lot done (phew). I really liked how you decided to move the axios call to an action and to update both the database and Locale state at the same time. I did not find anything major to point out. Your code looks clean and well organized.

**Review by kevkenshi-max — APPROVED** [review]
Nice work, Anastasia. It's crucial to connect with redux to make it dry and cleaner code.

**Review by Ogden-R — APPROVED** [review]
looks great! i love that you not only connected state to props, but also updated the okta signin-widget, and connect everything together so beautifully! it looks like you were very thorough in your planning! keep it up.

**Review by jose-mercado — APPROVED** [review]
Great work on hooking things up to redux! I do see that there are some conflicts with the package.json and package-lock.json, but aside from that, which should be an easy fix, the work looks great!

**Pull request merged**
