### PR TITLE
BL-474-fe-i-want-to-be-able-to-add-courses

### PR DESCRIPTION
**Pull request by techlando**
## Description

When I am managing the program, I want to be able to add courses, so that parents can find the courses when they are searching.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/8d5ae377e62e47e99b3a4a1036500d17

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by vasilii-garanin — DISMISSED** [review]
Hi guys, good job with code for an instructor to add courses. Looks like you brought in all the right imports. I like that you left a comment where code will have to be changed in the future. On side note, the driver/navigator partnership is also my favorite and I am glad it worked well for you.

**Review by dshipuk — APPROVED** [review]
Code looks great don't see any issues but I did notice in the file located in
src/components/pages/Registration/InstructorFlow_Step2.js
It seems like you guys have some code commented out that you guys forgot to remove

**Comment by techlando** [comment]
From instructor flow, and on, that code was added accidentally from another branch! I went back and deleted those lines in my last git commit, however those lines of code still reflect on GitHub...

**Comment by lisamdespain** [comment]
Looks great except I saw something small that might be a bigger deal later. In these 2 lines, "instructor" is misspelled:
import InstructorWelcome from './components/pages/Registration/IntsructorRegistration/InstructorWelcome';
import InstructorFlow_Step2 from './components/pages/Registration/IntsructorRegistration/InstructorFlow_Step2';

**Review by tkordysh — DISMISSED** [review]
Code looks good to me, and once the BE is sorted with giving admins the correct permissions it should be all set. Good job!

**Review by Roadlyfe — DISMISSED** [review]
nice, clean code.

**Review by reneetro — APPROVED** [review]
In the admin side bar I noticed that there is a an a tag labeled as "Edit Programs". Is this going to be to actually edit programs or the courses? Everything else looks really good and clean!

**Comment by Rlauckern** [comment]
Updated with the recent merges to main and i believe should no longer have conflicting branches.

**Review by dshipuk — APPROVED** [review]
Don't see any issues with spelling or code

**Review by Roadlyfe — APPROVED** [review]
revisions look good, clean code.

**Comment by gclancy121** [comment]
changes look good to me

**Pull request merged**
