### PR TITLE
BL 734 cleanup styling for admin add programs courses

### PR DESCRIPTION
**Pull request by laurensruiz**
## Description
Created separate .less files for each .js file, mad sure classNames are used, remove unnecessary in-line styling from the components. Note: some Ant Design components will need to have in-line styling, but normal html tags should be styled in a .less file.

## Fixes BL-734

https://bloomtechlabs.atlassian.net/browse/BL-734

## Loom Video
https://www.loom.com/share/453b9e8bc2a949aba36098d342d9e358

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
-
## Checklist:
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] I have removed unnecessary comments/console logs from my code
- [X ] I have made corresponding changes to the documentation if necessary (optional)
- [ X] My changes generate no new warnings
- [X ] I have checked my code and corrected any misspellings
- [X ] No duplicate code left within changed files
- [X ] Size of pull request kept to a minimum
- [ X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by EmmS21 — APPROVED** [review]
Great clean on the styling, massive impact on the look and feel of admin add program courses

**Review by Rlauckern — APPROVED** [review]
Much cleaner, great work and using the proper way of nesting the styling.

**Review by tkordysh — APPROVED** [review]
Nice job fixing the current styling and setting up future styling for success through your file structure design!

**Review by Irving-Delgad0 — APPROVED** [review]

**Review by Irving-Delgad0 — APPROVED** [review]
Great idea to make separate files to keep things clean and organized!

**Review by AlexiusThomas — COMMENTED** [review]
Code looks good, not seeing any obvious mistake

**Pull request merged**
