### PR TITLE
BL-195 Bug/fix website responsiveness

### PR DESCRIPTION
**Pull request by Benroberts37**
## Description

The signup flow was not responsive, so I used media queries and some CSS adjustments to make the flow more responsive. 

Fixes # (BL-195)

## Loom Video

[loom video](https://www.loom.com/share/c73a0bdf596c427280aa8c544252de92)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x ] I have made corresponding changes to the documentation if necessary (optional)
- [x ] My changes generate no new warnings
- [x ] I have checked my code and corrected any misspellings
- [x ] No duplicate code left within changed files
- [x ] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by spencerlonghurst — COMMENTED** [review]
The responsiveness that Ben did looks good. I can see the media queries and the styling changes done to better adapt the smaller screens. Great use of both rems and percentages!

**Review by DawsonReschke — APPROVED** [review]
Nice work Ben! I think that your loom video is not properly linked.

**Review by kylerostler — APPROVED** [review]
Loom video link is broken so you'll have to fix that to get the pr fully approved. As far as the styling goes I pulled down your branch and checked out your code and it seems a lot more responsive the sizing looks much better to me! Great work on this!

**Review by Ogden-R — APPROVED** [review]
looks very nice and accessible. great job making it work for all sizes of screens.  the layout changes look great.

**Review by leewp8 — APPROVED** [review]
The sign up flow looks a lot better. The responsiveness works really well and the code seems very neat and organized. Great job.

**Review by jose-mercado — APPROVED** [review]
Absolutely great work ben. as developers we know how important it is to style responsively and the work you did with the media queries really add value to the website as a whole.

**Pull request merged**
