### PR TITLE
BL-733 fixed bug in index.js. localhost now starts

### PR DESCRIPTION
**Pull request by Rebecca-Stone**
## Description

CoderHeros FE fails to build on npm run start because line 40 inside index.js is imported wrong. Needs to be "import Footer from './components/common/Footer/Index';"

Fixes # (BL-733)
https://bloomtechlabs.atlassian.net/browse/BL-733?atlOrigin=eyJpIjoiZmViYjk4MWRlZDA1NDc1M2IxYTJlODhhODJjNzAwN2IiLCJwIjoiaiJ9

## Loom Video

https://www.loom.com/share/98a452b744934af7b077d0b520026c3c

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by EmmS21 — APPROVED** [review]
Simple but very valuable fix.

**Review by laurensruiz — APPROVED** [review]
Nice catch finding this error!

**Review by Rlauckern — APPROVED** [review]
Good job. Simple fix that makes a huge difference!

**Review by tkordysh — APPROVED** [review]
Thank you for catching this, well done!

**Review by sklanier — COMMENTED** [review]
Nice! Beat me to it!

**Pull request merged**
