### PR TITLE
implement unit tests for participation features

### PR DESCRIPTION
**Pull request by kevkenshi-max**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by kevkenshi-max** [comment]
https://www.loom.com/share/94389412ed654ac1a67577f0a8706027

**Review by AnthonyLayne — DISMISSED** [review]
Your tests look good, I only have one suggestion that is more nit-picky than anything. On line 22 in PaymentSuccess.test.js, you have 'PaymentSuccess />', would recommend changing it to '< PaymentSuccess />' or just 'PaymentSuccess'. Other than that it looks great, good job!

**Review by Cassius-Cassity — APPROVED** [review]

**Review by Irving-Delgad0 — APPROVED** [review]
I like what you did with the widget. it looks a lot cleaner that way!

**Review by Rlauckern — DISMISSED** [review]
The tests work and seem consistent for the design. Clean and well done.

**Review by tkordysh — APPROVED** [review]
Tests look good! This will help future upkeep of the application to make sure any new features don't break existing functionality. Well done!

**Review by ivanovicuros — DISMISSED** [review]

**Review by techlando — APPROVED** [review]
Good descriptions on unit test. Nice job using the beforeEach.  A-lot of files are changed though..

**Review by vasilii-garanin — DISMISSED** [review]
Hi guys, good job writing tests to check for successful payment. I like that in your video you show us tests working correctly and also failing when you change the expected values. Code looks good, I like that you left relevant comments for future developers.

**Pull request merged**
