### PR TITLE
Bug/navbar transition

### PR DESCRIPTION
**Pull request by jimjamesjimathy**
I resized the font for the nav_Links as I thought they were too small for the screen. I also used flexbox to give the links equal amount of room in the navbar component. I added border-right to each link to make the navbar not look so bland. I deleted the text-decoration as it does not transition like other properties such as color and background-color, and so instead I just increased the font-size and letter-spacing on hover. The buttons for "Contact us" and "Login" were using percentages for the border-radius which gives an ugly look (unless trying to make circles) so I switch to px to get a nice rounded edge. 

Fixes # ( nav-link transition being choppy )

## Loom Video
 - https://www.loom.com/share/aca287efdb4c4460a22295fffef6d912
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by bezzantsam — APPROVED** [review]
The styling changes are evenly spaced and visually appealing. The text underline was a great choice and having them increase in size when hovered over is more accessible.

**Review by AndrewGary — APPROVED** [review]
Great changes James, site looks way better than before!

**Review by Sug4rSku11 — COMMENTED** [review]
I like the border right and increased font size when hovering, makes reading the words easier. Looks nice with the navbar lined up.

**Comment by rjgeng** [comment]
You are always doing a better job on styles. It looked better than before. I like what you are doing!

**Review by rjgeng — APPROVED** [review]
very better styling, I feel shame of all try before!

**Pull request merged**
