### PR TITLE
fixed responsiveness for parent home page

### PR DESCRIPTION
**Pull request by Benroberts37**
## Description

This is another page we have made responsive - still some more to go. 

Fixes # (issue)

[## Loom Video](https://www.loom.com/share/0aeaee796ff64ed1aeab775908fe8476)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by Benroberts37** [comment]
@EmmS21 and i worked on this one together

**Review by brandib222 — APPROVED** [review]
Great job fixing the responsiveness! It's details like this that make a huge difference. I would just sift through the warnings to see if there's anything you can easily get rid of, but otherwise, looks great!

**Review by spencerlonghurst — APPROVED** [review]
Looks great! I see no issues in your code along with no typos or comments or mistakes. Great job guys!

**Review by jose-mercado — APPROVED** [review]
I really like what you did to make the buttons for the parent home page more responsive. The slight indent for the "add student" definitely needed to be changed. Along with the media query to make it responsive for mobile screens, this looks great!

**Review by joseph-fantuzzi — APPROVED** [review]
This is a minor change, but effective! The loom video does a great job explaining what needed to be fixed and the steps you took to resolve the problems. Responsiveness issues can really be a pain, so I appreciate you taking the time to fix it. Overall, great work!

**Review by anastasia-lapteva — APPROVED** [review]
Hello Ben and Emmanuel,

I really enjoyed your demonstration of the webpage responsiveness before and after your implemented code. Great job fixing both the button alignment and text sizes! These are small but significant changes that elevate the experience of using this webpage.

**Review by ashtilawat23 — APPROVED** [review]

**Review by Ogden-R — APPROVED** [review]
my OCD thanks you for straightening that out. great job with your media-queries!

**Pull request merged**
