### PR TITLE
BL-738 consolidated add courses and edit programs tabs into the  cour…

### PR DESCRIPTION
**Pull request by kevkenshi-max**
…ses tab on the admin sidebar

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by kevkenshi-max** [comment]
https://www.loom.com/share/def111e1e4c4403d97f22fb5cdd2d53a

**Review by techlando — APPROVED** [review]
Nice cleanup on the code. 👍

**Review by Rebecca-Stone — COMMENTED** [review]
Clean up looks great! But your pull request is missing some details in the description, type of change and checklist.

**Review by reneetro — APPROVED** [review]
Seems like there might be some unused variables now, not sure if you will need them down the road. Everything looks good and clean!

**Review by Roadlyfe — APPROVED** [review]
everything looks good. clean code.

**Review by AnthonyLayne — APPROVED** [review]
Nice and simple, great job guys. Also, thanks for fixing line 22 in the tests!

**Comment by Cassius-Cassity** [comment]
Really Concise!

**Review by Cassius-Cassity — APPROVED** [review]
Really concise!

**Review by Rlauckern — APPROVED** [review]
Nice clean and organized. Good job!

**Review by vasilii-garanin — APPROVED** [review]
Hi guys, good job with cleaning up extra tabs on sidebar into single Courses tab. I like that you showed us all 3 tabs on deployed site so we could see what tabs you wanted to remove. The single Courses tab looks much better, less confusing  for users.

**Review by tkordysh — APPROVED** [review]
Looks much cleaner now, good job!

**Pull request merged**
