### PR TITLE
BL-147 fe as a user i can message other users

### PR DESCRIPTION
**Pull request by dirkknibbe**
## Description

Created a universal messaging sidebar that will enable any user to use messaging functionality to message any other user. Each user has a message inbox specific to them. We passed this component to all the available messaging routes. We created dummy data for redux but are still waiting on backend endpoints so it can be fully connected to the database. 

Fixes # BL-147-fe-as-a-user-i-can-message-other-users

## Loom Video

https://www.loom.com/share/c5747c60e81c44649917c174a0ae9e62

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by joseph-fantuzzi — APPROVED** [review]
This is probably the best implementation I've seen in Labs thus far! It takes a lot of work to get a messaging system to work and you guys did a fantastic job. The loom video clearly explains the intent of this ticket and the process you took to solve and implement this into the codebase. Your code looks efficient, clean, and maintainable. Awesome work!

**Review by jose-mercado — APPROVED** [review]
Great work creating a messaging component that's not just specific to a child or parent account, Looks really well built out and I thought the loom video was really descriptive and informative. Overall, great work!

**Review by ShahWahidy — APPROVED** [review]
Great functionality. The component is written clean and organized, the loom video is very informative. You covered a lot on this ticket, well done!

**Review by tvolchko — APPROVED** [review]

**Review by anastasia-lapteva — APPROVED** [review]
Hello Dirk and Michael,

I agree with another comment above that this is the best implementation I have seen in Labs! Your Loom video is very informative and well done. Thank you for walking us through each change. Great job making a universal framework in ParentHome component so that it may be utilized by other components. I want to commend your organizational skills in moving all message-related components into a Messages folder. Your HandleClick to highlight a selected thread is well executed. I also love your attention to detail in sorting latest messages at the bottom and latest threads at the top. Overall you did a fantastic job with the front end, can't wait to see it hooked up to backend!

My only note is stylistic and has nothing to do with you, as I'm sure you based designs on Figma. But I wonder why the button to send a message is labelled "add comment," a phrase typically used to leave comments on posts rather than for messaging apps?

**Review by Ogden-R — APPROVED** [review]
great job grouping and sorting the senders so that conversations are easier to send and recieve. i like that it filters through so that you only get the convos relevant to the user.

**Pull request merged**
