### PR TITLE
BL-579 Ensure book now button redirects to add courses and renders ap…

### PR DESCRIPTION
**Pull request by EmmS21**
…propriate component

## Description

Adding functionality to ensure that the Book Now button redirects to the appropriate route and as a consequence rendering the correct component relevant to the route

Fixes # (issue)

Book Now button did not redirect the user to any route

## Loom Video

[Please paste a link here of a quick loom video walking through what you did in your PR .
](https://www.loom.com/share/f82c92456f7e493ea6f7061b8b3cfabb)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Ogden-R — APPROVED** [review]
Looks great! isnt it funny how the tiniest little change in syntax can make such a huge difference?! great attention to detail in fixing this.

**Review by anastasia-lapteva — APPROVED** [review]
Hello Emmanuel and Rebecca,

Thank you for requesting a review from myself, that was a cool notification to receive. I think your Loom video is great, it is concise and shows us exactly what we need to see - a functioning redirect upon clicking the "book now" button. Your code looks clean, I don't see any lingering commented-out code. Great job!

**Review by Michael-Subbarao — APPROVED** [review]
A small but valuable fix. The code looks clean and only changed what was necessary.

**Review by Rebecca-Stone — COMMENTED** [review]
I love the simplicity of the changes. When this is merged, it will definitely make future tickets easier! I think we did great on this!

**Comment by laurensruiz** [comment]
Great job fixing this. Even small issues can cause major problems so this waa a great simple fix!

**Review by laurensruiz — APPROVED** [review]
Great job fixing this. Even small issues can cause major problems so this waa a great simple fix!

**Pull request merged**
