### PR TITLE
Adds and styles Landing page

### PR DESCRIPTION
**Pull request by manny-glez**
First version of the landing page, renders in /landing. Not perfect and uses placeholder images.
loom: https://www.loom.com/share/e53f215006d844ca93dbf6de6f5c952d

### CODE REVIEW

**Review by TraNequaFauntleroy — COMMENTED** [review]
I like how you indicated that this is still a work in progress in the description. I would like to see more commits though, being as though this feature took a lot of code to build out. Overall, you got a lot done and its starting to look like the wireframe.

**Review by Pauline122112 — CHANGES_REQUESTED** [review]
Can you import main footer to the landing.

**Review by Pauline122112 — COMMENTED** [review]
You are receiving an eslint error in regards to importing Link from a dependency which is used for the code on line 96 which is currently not in use at the moment because it is commented out.

**Review by cqian12 — APPROVED** [review]
Looks good, let me know if you need any help with the linting error

**Pull request closed without merging**
