### PR TITLE
Feat/media queries admin

### PR DESCRIPTION
**Pull request by CaitlinTalbert**
## Description

Ticket BL-195: reformat all available components for responsive design. My part was to make the submit a new program page responsive at 1200px, 768px, and 576px. I also found that there was an empty component on this page showing a box with nothing in it. I found that this component was called AdminAddCoursesList inside a div classname of admin-add-courses-right and I could not find this component anywhere so it was deleted and now the empty box is gone. Can be easily added back if needed. 

Fixes # (issue)

## Loom Video

https://www.loom.com/share/f443421af1984f0285946a60c98c3d7a

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Benroberts37 — APPROVED** [review]
Nice job Caitlin. Media query looks good and makes the page responsive. Also, nice job investigating and finding out that the box was linked to a component that doesn't exist. The page looks a lot better now.

**Review by anastasia-lapteva — APPROVED** [review]
Hello Caitlin,

Thank you for showing the bug on your locally deployed webpage (it looked pretty funny before your fix). Good thinking taking initiative to consult with Ben and remove the unnecessary empty component (AdminAddCoursesList). Overall your code looks clean and dry. You did a great job implementing media queries!

**Review by jose-mercado — APPROVED** [review]
Great job adding media querys to make the page a lot more responsive as well as taking out the unnecessary "AdminAddCourseList" from the programs page components. Looks fantastic

**Review by ivanovicuros — APPROVED** [review]

**Review by JakeHappel — APPROVED** [review]
Good work the media query looks good and good catch on the dead code!

**Pull request merged**
