### PR TITLE
Feature/family home styling

### PR DESCRIPTION
**Pull request by magoha01**
## Description

This pull request focused on implementing the finalized Figma design for the Family Page into the project, adding functionality to the parent "view account" button, adapting all styling to use theme imports and responsive units, and editing the parent sidebar to match options in the parent flow.

Before:
Screen Shot 2022-05-02 at 4 40 51 PM

After:
Screen Shot 2022-05-02 at 4 42 48 PM

## Loom Video

https://www.loom.com/share/bcbcefabc5e8499fa1ae998c6270739b

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by dconley1212 — APPROVED** [review]
Nice work! Looks great!

**Review by ElchinNasirov — APPROVED** [review]

**Review by peterdavidconley — APPROVED** [review]
Nice job removing redundant code i.e. <Sider> component in multiple instances.  Slick use of Ant Design components, saving yourself time and energy from creating the code from scratch. Impressive use of !important to override Ant Design styling.

**Comment by nyamekyeannor** [comment]
Amazing job using Ant Design components. I know Ant can be challenging but you implemented it seamlessly. I also like the use of "!important" to override the Ant styles. I actually learned about that yesterday. Neat work with omitting commented code and using responsive units Hailey!

**Review by nyamekyeannor — COMMENTED** [review]
Amazing job using Ant Design components. I know Ant can be challenging but you implemented it seamlessly. I also like the use of "!important" to override the Ant styles. I actually learned about that yesterday. Neat work with omitting commented code and using responsive units Hailey!

**Review by lizzythomson — COMMENTED** [review]
This looks awesome! Great work!

**Pull request merged**
