### PR TITLE
Feature wireframes

### PR DESCRIPTION
**Pull request by TraNequaFauntleroy**
I simply added the wireframes (src >> wireframes >> Desktop.png or Mobile.png) to the codebase for this and future cohorts to easily have access without having to ask their UX engineers for it.

Video explanation: https://user-images.githubusercontent.com/86528475/146051490-75c9b0ac-1b5d-4cf6-8764-e4df453c9b93.mov

HELP: for some reason all of my prior commits from another branch on this on PR. I don't know why it keeps doing that. Please advise, if you can.

### CODE REVIEW

**Review by stevenjhomem — APPROVED** [review]
Looks good to me! Keep up the good work!

**Comment by vannguyen141290** [comment]
good job! I always love your design. excited to see the next designs :)

**Review by zach-morris-txt — CHANGES_REQUESTED** [review]
This may help with transferring commits to the proper branch:
https://stackoverflow.com/questions/2941517/how-to-fix-committing-to-the-wrong-git-branch

Another important note, this PR also has the package-lock.json in the "Files Changes". *See my previous "request changes", Ash cannot merge until that has been rebased out of there

**Review by zach-morris-txt — APPROVED** [review]
Wireframes added. Not entirely certain what's going on w/ TraNequa's branches & commits. I've tried to rebase and drop the incorrect commits but for some reason that just added several new commits without correcting the old ones (even with a proper rebaser GUI running). It's not a failing issue and too loaded to correct for now.

**Pull request merged**
