### PR TITLE
BL-833 fixed logout button not appearing

### PR DESCRIPTION
**Pull request by gclancy121**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes the logout button not appearing when you login with llama001@maildrop.cc
Fixes # (issue)
BL-730
## Loom Video
https://www.loom.com/share/e13a2697d38d4253887faaa05ab61c43
Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by reneetro — DISMISSED** [review]
Looks great, nice work fixing this bug! I noticed a console log in in the NavLinks and userActions but everything else is great!

**Review by lisamdespain — DISMISSED** [review]
Looks great with a couple comments/questions. There are a handful of console.logs in the files. Are they still necessary? Other question: was this change based on what was coming back from Okta, and if so, will everything that uses axiosWithAuth middleware be affected? I'm thinking it could be good for other components, but I'm unclear what the overall effect will be.

**Review by reneetro — APPROVED** [review]
Awesome job cleaning up the code, yay for bug fixes and no console.logs 😄

**Review by macrowell70 — APPROVED** [review]
Good job.  The code looks a little cleaner now too. So that's a plus

**Pull request merged**
