### PR TITLE
Bl 139 fe as an instructor i can see current courses i am teaching

### PR DESCRIPTION
**Pull request by Ogden-R**
## Description

We made a page for the instructor to view their classes all at once, but also able to click on a class to get more details.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/a0f03a484f03443b90959cc88174b4e2

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by anastasia-lapteva — APPROVED** [review]
Hello Rebecca and Danny,

Your styling for the Courses page looks great! I like that you added to the skeleton provided on Figma while keeping usability in mind. I agree with your assessment that displaying all relevant classroom info will prevent confusing (and unnecessary) page jumping. I'm sure instructors are very busy, and your thoughtful layout streamlines presentation of classroom info, making the instructor's job easier.

**Review by JamesFincher — APPROVED** [review]
Nice and clean styling. Matches the website well!

**Review by jose-mercado — APPROVED** [review]
Great job adding courses to the instructor dash. Visually it looks super satisfying and the code looks exceptionally clean. Love the work put into this, fantastic job

**Review by Michael-Subbarao — APPROVED** [review]
The Stylings look great. Also great job working around the back end. It looks like it'll be pretty easy to hook up to the backend once its ready compared to the hard coding a lot of people have done in the past.

**Review by JakeHappel — APPROVED** [review]
The code looks very clean and the styling is great. good job!

**Review by Benroberts37 — APPROVED** [review]
Great job. Love that you can see the most relevant and important information on the cards so they don't have to click in each time. The styling and spacing looks great. Nice job!

**Comment by laurensruiz** [comment]
Amazing job styling these and implenting the code.  I also liked how you considered how an Instructor would feel when going through the flows so that the user experience would be a lot easier.

**Comment by Rebecca-Stone** [comment]
The styling looks great, and the layout is very appealing! Changing the button to say 'classroom' instead of a pen was definitely a good call along with displaying some of the info on the cards already. Great job!

**Review by Rebecca-Stone — APPROVED** [review]
The styling looks great, and the layout is very appealing! Changing the button to say 'classroom' instead of a pen was definitely a good call along with displaying some of the info on the cards already. Great job!

**Pull request merged**
