### PR TITLE
fixed a capitalization error in the footer index.js

### PR DESCRIPTION
**Pull request by Roadlyfe**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/39f7bf866a4746a9bdda6c837f8a7f00

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by lisamdespain — APPROVED** [review]
I noticed that same error and just fixed it locally. Curious if just changing the filename to lowercase and _not_ adding /index to this file would do the same thing?

**Review by dshipuk — APPROVED** [review]
Noticed the same problem earlier today fixed it on my branch, but great job!

**Review by techlando — APPROVED** [review]
this error has been haunting some npm starts... glad its fixed! good job

**Comment by gclancy121** [comment]
Good job catching this, error, I'm glad it's fixed

**Pull request merged**
