### PR TITLE
added parenthome and parentboking loom explaination

### PR DESCRIPTION
**Pull request by huiminzhang0111**
[Parent booking]
https://www.loom.com/share/4e67eaa920604c528bae69126b5b805f 
**code logic**: we mainly want to render ‘AvailableCourses’ components, along with some design-purpose components like ParentSidebar and Banner. In availablecourse, the code implemented react-redux, and stored the state in the ParentReducer. If we look at the return section, we can tell that it wants to render ‘renderTab’ function when we click on different tabs with assigned keys. Each tab would return the filtered condition. Each course is using ‘ParentBookingCard’ as common component, which adds efficiency to our code. 
**improvement**: there are redundant design, in ‘ParentBookingCard’, ‘continue booking button’ seems not doing anything; each card layout is not fitting the screen size, which is due to parent index.less; there is only one specific image for every course, we can make it more flexible by interacting with backend down the road; in ‘AvailableCourses’, the 1:1 session button is not doing anything, just plain text, we can make it more functional by adding filter function; as for other tabs, I don’t think they are making any actual difference; overall, I feel it’s not necessary to implement redux if we are only storing the state, without dispatching any actions. 

[Parent home]
https://www.loom.com/share/a504cdd1f56b4751ad61c09c0d3e395b 
**Code logic**: there are several components in this directory, but the code so far is only focusing on ‘ParentCalendar.js’ and ‘ParentSidebar.js’ as design purpose. ParentCalendar is importing states from ParentReducer.js via redux. We are passing ‘dateCellRender’ and ‘monthCellRender’ functions to Calendar component. As for dateCellRender, we are getting session data by mapping corresponding date, so it can show up in each date cell. There are two types of buttons in the datecell, one is show full, once we click the button, showfull function would set showfullprogram (boolean) to be true if we have a date match, we are getting a modal with a list of programs for that day. The other button type is for each course with its own schedule_id, once we are matching the activeModal by clicking the button and matching the schedule_id, we are getting info for that specific course. The other main function would be monthCellRender, which does not make any sense right now. 
**improvement**: isModalVisible seems being redundant here as it simply set to ‘false’ initial status; in the getListData function, listData is set to an empty string, so I don’t think the if statement below is doing anything, it will directly go to the else case; monthCellRender function is not making any sense; if we go to ParentHome/index.js, we can notice it is passing dummydate to parentcalendar, but actaully using redux to acquire the data, so I think we can only keep one way to store the state; handleOk and handleCancel are both setting setActiveModal back to 0, which does the same thing, only one ok or cancel button is needed here; most componets are not in use right now.

### CODE REVIEW

**Review by Pauline122112 — APPROVED** [review]
Amazing job with the Loom videos, Huimin! They were very informative and easy to follow. You were able to mention the areas that needed improvement in regards to the ParentHome folder where you were able to identify the components that were not imported or in use. I found your explanation to be very thorough and convincing. Well done!

**Review by stevenjhomem — APPROVED** [review]
Wow. 

That was so thorough and well explained. Teams after us are going to be so thankful!

**Comment by cqian12** [comment]
Great work! I really like the write ups for code logic and suggested improvements, planning to incorporate that into my own loom video PRs in the future. Agree with the suggested improvements

**Review by cqian12 — COMMENTED** [review]
Great work! I really like the write ups for code logic and suggested improvements, planning to incorporate that into my own loom video PRs in the future. Agree with the suggested improvements

**Comment by ehsan2793** [comment]
wow, awesome work, very detailed and well explained

**Pull request merged**
