### PR TITLE
bug/fixing footer responsiveness

### PR DESCRIPTION
**Pull request by EmmS21**
## Description

Making the footer fully responsive on mobile

Fixes # (issue)

## Loom Video
[Please paste a link here of a quick loom video walking through what you did in your PR .
](https://www.loom.com/share/4a63892cd05a4bb780d0dc6b35370aa6)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

Worked with @Benroberts37 on this

### CODE REVIEW

**Review by brandib222 — APPROVED** [review]
Definitely needed. I would just review some of the warnings. It looks like there are quite a few things that may not be needed and could easily be taken out. Otherwise, great job fixing the footer responsiveness!

**Review by Benroberts37 — APPROVED** [review]
Nice job Emmanuel, it was great to work with you on this and make the footer more responsive on mobile. It reads a lot better and is more in line with what a lot of other companies do with their mobile footers.

**Review by joseph-fantuzzi — APPROVED** [review]
Great work! Mobile responsiveness is really important as it provides users with a rich user experience for smaller device sizes. Taking the time to fix the mobile view of the footer was a great idea. The only thing I would suggest is visually showing how the responsiveness of the footer layout on mobile has changed from before your code implementation to after. Other than that, job well done!

**Review by ShahWahidy — APPROVED** [review]
Good catch Emmanuel. Great implementation of media queries. code looks nice and clean.

**Review by tvolchko — APPROVED** [review]

**Review by anastasia-lapteva — APPROVED** [review]
Hello Emmanuel and Ben,

At a glance the code looks clean and dry. There is no leftover commented-out code. From reviewing your previous PRs, I am confident that you did a good job with this ticket. However, this Loom video is not as comprehensive as usual. From what I have seen of your previous work, you typically demonstrate the problem and walk us through your solution. This time, the Loom video was a reading of your ticket description.

**Pull request merged**
