### PR TITLE
Initial mockup for instructor's landing page

### PR DESCRIPTION
**Pull request by krisf451**
## Description

Initial mockup for the instructors landing page per design file given to us by the stakeholders.

## Loom Video
(https://www.loom.com/share/3c30ad64c593481a942fcd574673ff20)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by mcmillanj — APPROVED** [review]
Approved

**Review by Cheyenneb96 — APPROVED** [review]
thank you for a wonderful loom video to follow.

**Review by PriscilaMonteiro — APPROVED** [review]
Great job creating the initial mockup for instructor's landing page. One thing that we should check is if those images are commercial free.
Format looks great.

**Comment by paulstgermain** [comment]
This is a great PR that begins to add a sorely needed piece of our application - the UI!

A couple of pieces of feedback here though:

1. Let's try and make our PR descriptions a little more descriptive moving forward!
2. Try to keep your PR sizes to a minimum - remember, you still need to have submitted or paired on **5 PRs** before the end of next week to graduate at the first opportunity! I would have broken this down and submitted a PR for each subpage here.

**Pull request merged**
