### PR TITLE
Bug/footer media queries

### PR DESCRIPTION
**Pull request by jimjamesjimathy**
I reformatted the flex box on the footers desktop and mobile version to center the elements and text as well as take out the padding so that neither of the footers elements get pushed to the wrong areas when being resized.

Fixes # ( footer content not aligning correctly on screen resizing )

## Loom Video

 - https://www.loom.com/share/8dac8c02309a40d688761b7941206e43

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ivanovicuros — APPROVED** [review]

**Review by AndrewGary — APPROVED** [review]
Again, great work with the page design. It says there will be merge conflicts but I assume those will disappear once your earlier PR's get merged

**Review by Sug4rSku11 — APPROVED** [review]
Great job adjusting the footer. Looks much better centered on all screen sizes.

**Comment by rjgeng** [comment]
You always make the layout better than before, and you did huge work in our group!

**Review by rjgeng — APPROVED** [review]
Centered and size changed made it better than before!

**Pull request merged**
