### PR TITLE
path properties fixed

### PR DESCRIPTION
**Pull request by ivanovicuros**
## Description

fixed invalid DOM property.
Console was flashing several different errors and guidance how to get them fixed. 

## Type of change

Bug fix (non-breaking change which fixes and issue)

## Loom recording

https://www.loom.com/share/fad97445c9134507a4cc07fc275e10fc

### CODE REVIEW

**Review by aaronpear — APPROVED** [review]
Nice quick changes!

**Review by JakeHappel — APPROVED** [review]
good update

**Review by Adamh1990 — APPROVED** [review]
much better, good changes

**Review by ElchinNasirov — APPROVED** [review]

**Review by paulstgermain — CHANGES_REQUESTED** [review]
Great catch here! That said, this PR _does_ need a Loom video walking us through the changes made. As soon as you add a link to one and flesh out this description some more, this PR will be ready to merge!

**Please DM me once these changes have ben made!**

**Review by paulstgermain — APPROVED** [review]

**Pull request merged**
