### PR TITLE
Feature/adminaddcourses

### PR DESCRIPTION
**Pull request by natecheney-dev**
## Description
Basic implementation that allows admins to create, edit, view, and delete course programs. Built out reducer and action files for handling state and performing CRUD operations once the backend is ready. Three future PRs that could be implemented for this feature could be, connecting it to the backend, styling, and form validation for both creating a program and editing a program.

## Loom Video

[Loom Video](https://www.loom.com/share/32216a0db4564a0eb6de2e7e550458d9)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by 19jlevitre — APPROVED** [review]
Everything looks great. I really like how many commits you had and how descriptive they were. This is really useful and clean. Great work

**Review by Cheyenneb96 — APPROVED** [review]
it looks great cant wait to have it hooked up to the back end!

**Review by mcmillanj — APPROVED** [review]
great job with that implementation

**Review by ElchinNasirov — APPROVED** [review]
Looks great.

**Pull request merged**
