### PR TITLE
removed the duplicate buttons on the sidebar for the parent dashboard

### PR DESCRIPTION
**Pull request by Ryan-E-Mark**
## Description

Removed the duplicate buttons that were appearing on the sidebar of the parent dashboard. The buttons were hardcoded into the sidebar component, I simply removed the repeated code.

Additionally, changed the logout button route from /logout to /landing so that a user is redirected to the landing page after logging out.

Link to trello card corresponding to this task: https://trello.com/c/SNVQkMsu/116-duplicate-buttons

Link to Loom recording: https://www.loom.com/share/3a14d644db904fcdb69bc62d3b51aa18

Fixes # (duplicate sidebar buttons)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by pjaepole** [comment]
I learned from my own pull request, that you can push only needed file for git push

**Review by alextcedwards — CHANGES_REQUESTED** [review]
Enjoyed the video, explained everything nicely. looks good, well done mate.

**Review by nforman91 — COMMENTED** [review]
Great explanation of simple fix! I appreciate the route change detail, and taking the initiative to do this. I assume there will be more complex bugs in the future!

**Review by pjaepole — APPROVED** [review]

**Review by MatthewMion — APPROVED** [review]

**Review by MatthewMion — APPROVED** [review]

**Comment by RoseGabriely** [comment]
> Enjoyed the video, explained everything nicely. looks good, well done mate.

Hey, it looks like you requested changes, but your comment didn't explain something to be changed so I will close this request. Feel free to reopen it if you were intending to ask for changes.

**Pull request merged**
