### PR TITLE
Bl 478 fe i want to be able to pay for the course booking

### PR DESCRIPTION
**Pull request by Rebecca-Stone**
## Description

When I am exploring programs for my child, I want to be able to purchase a course, so that I can officially sign my child up for the class.

Work with the designs from https://bloomtechlabs.atlassian.net/browse/BL-473 for this feature.

There are two parts to the feature:
- Booking component (as designed by Lauren Ruiz and Anthony Layne)
        -This is the selection page for a parent to choose which class and how many seats to continue to a payment confirmation page
- Payments component
        -This includes integrating Stripe payment in the “shopping cart” section.

Fixes # Bl-478 https://bloomtechlabs.atlassian.net/browse/BL-478?atlOrigin=eyJpIjoiNjFmOGRhNGVkM2FiNDQ2OTk0NTA3NWY5OGFmNDJhNDAiLCJwIjoiaiJ9

## Loom Video

https://www.loom.com/share/364b07b20527416280177edc75d5bb94

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by EmmS21 — APPROVED** [review]
Like the styling, code looks clean and well written.

**Review by laurensruiz — APPROVED** [review]
Good implementation of our design. I like how you also added comments to make sure anyone working on this can be redirected to the right place. Code looks clean as well

**Review by Michael-Subbarao — APPROVED** [review]
Great job, nice stylings and very useful comments in the code for the future. The loom video is also very concise and well presented.

**Review by Irving-Delgad0 — APPROVED** [review]
looks great, just some of the spacing is inconsistent at least in the styling files

**Review by tkordysh — APPROVED** [review]
Implementation of the designs looks great! I like the styling and the code looks good to me. Well done!

**Review by AlexiusThomas — COMMENTED** [review]
revisions look good, clean code.

**Pull request merged**
