### PR TITLE
BL-106 Built out student Portfolio component 

### PR DESCRIPTION
**Pull request by spencerlonghurst**
Co-authored-by: William Lee leewp8@gmail.com
Co-authored-by: Jose Mercado josefmercado99@gmail.com
Co-authored-by: Ahmad Wahidy shah.wahidy@gmail.com

## Description

We built out the student portfolio component. We brought in some previous Less styling, but the scaffolding is there and is prepared and ready to be styled into exactly what it needs to be.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/84aa05b829ee4ec2b3442e17735878d7

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Benroberts37 — APPROVED** [review]
Nice work everyone. The page and code looks good after reviewing over it and seems to fit nicely in with the rest of the site in terms of aesthetics and the current styling. Nice job on the alt text for the images as well to make the page very accessible.

**Review by dirkknibbe — APPROVED** [review]
Nice work guys! Big up for making sure to follow the Figma designs nice job!

**Review by kylerostler — APPROVED** [review]
Clean components with a good skeleton for styling and work to be done later if needed. Looks good no comments in the code or console.logs mudding anything up.

**Review by Ogden-R — APPROVED** [review]
Looks great. The route to the student portfolio as well as the layout of the cards look very clean and organized.

**Pull request merged**
