### PR TITLE
Bl 462 fe i want to find information that will tell me about coder heroes

### PR DESCRIPTION
**Pull request by kevkenshi-max**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by kevkenshi-max** [comment]
https://www.loom.com/share/4da11d9222ab46bf895c779b25e1a2b6

**Comment by kevkenshi-max** [comment]
https://www.loom.com/share/4da11d9222ab46bf895c779b25e1a2b6

**Review by CaitlinTalbert — APPROVED** [review]
Great job guys! The styling flows with the rest of the website and makes it feel like it's really coming to life.

**Review by Ogden-R — DISMISSED** [review]
Looks great! i love that you added lorem ipsum so that the pages are full of info. thats a nice touch. very clean code and clearly marked classnames.

**Comment by tkordysh** [comment]
Looks good to me! Will need to hear back from Brianne about what content to put in place of the lorem ipsum placeholders, but as far as the structure and layout is concerned I think you guys did a great job.

**Review by Michael-Subbarao — APPROVED** [review]
The changes look good, I like that you added in all of the placeholder pages for future learners. I'm not sure what the changes for the package-lock.json are for though.

**Review by Benroberts37 — DISMISSED** [review]
Nice job, the styling looks great and goes well with the rest of the site. Having a footer with all working links will be great.

**Review by leewp8 — DISMISSED** [review]
Nice job guys. Code looks sharp, and the CSS work looks really neat and organized. Great job!

**Comment by laurensruiz** [comment]
Good job! The styling looks great and is easy to understand from a user perspective. The CSS looks really neat as well!

**Pull request merged**
