### PR TITLE
fixed typo on components name and replaced with right spelling

### PR DESCRIPTION
**Pull request by pjaepole**
## Description

https://trello.com/c/DV0vFHdN/133-bug-parentbookingcontainer-component-has-a-typo
ParenBookingContainer typo fixed and replaced all import and export with the right spelling.

Fixes # (issue)
Typo

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by alextcedwards — APPROVED** [review]
Thanks for this!!

**Review by Ryan-E-Mark — APPROVED** [review]
Great pickup, better to fix these little issues before they cause headache down the road!

**Comment by seanmp3** [comment]
Not all heroes wear capes, Nice catch!

**Review by nforman91 — COMMENTED** [review]
Thanks for doing this, this was caught by Ryan & I while pair programming. If anyone sees any other issues like this, do the same as this! Great work!

**Review by RoseGabriely — COMMENTED** [review]
Looks great thanks!

If you haven't already I'd use the built-in search all feature in vscode to check for any instances of "ParenBookingContainer" you may have missed, just to make sure nothing breaks with these changes. If you have then this PR is all set!

**Review by RoseGabriely — APPROVED** [review]

**Review by seanmp3 — APPROVED** [review]
Not all heroes wear capes, Nice catch!

**Pull request merged**
