### PR TITLE
Created a My Tasks component for the student flow based on the figma …

### PR DESCRIPTION
**Pull request by leewp8**
…design

Co-authored-by: Spencer Longhurst spencersean12@gmail.com
Co-authored-by: Ahmad Wahidy shah.wahidy@gmail.com
Co-authored-by: William Lee leewp8@gmail.com

## Description

Created a "My Tasks" component for the student flow. Added a route, banner, and sidebar functionality to go along with the student-tasks page.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/282fcffa9e0848bf98ffbb08ca2e9c5f

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by kylerostler — APPROVED** [review]
Component looks good aside from needing some styling. Would love to see it connected to the redux store but that is probably work for another ticket. Assuming the missing 29k files from package-lock is because of the bug we were experiencing earlier this week and you just deleted that file. All in all very clean no unecessary comments or anything of that nature.

**Review by Ogden-R — DISMISSED** [review]
looks really nice. great job completing the path making sure it works. may want to try using a dummy data or something, instead of hardcoding it in, but it looks like you were really thorough.

**Review by brandib222 — DISMISSED** [review]
I would just make sure all of those divs are necessary, because I know they don't like us to go crazy with them. But otherwise, a great start!

**Review by Benroberts37 — DISMISSED** [review]
Don't have too much more to add than what the others mentioned above. I think the code looks clean and is structured well, and if the scope for this ticket was just building out the front-end, it looks great. Good job

**Review by anastasia-lapteva — APPROVED** [review]
Hello William, Spencer, and Ahmad,

Thank you for showing the basic design you have created. It looks very good so far! Your team is on the right track. Like previous comments mentioned, your code looks clean and dry.

**Comment by laurensruiz** [comment]
The basic design looks really good and structured well. The code looks very clean as well. The functionality is great but instead of hardcoding the data, I suggest working with dummyData to implement a more accessible code.

**Review by wreck888 — APPROVED** [review]
The code looks good! With some more css styling it will look great! Maybe using the card styling in other figma designs elements with more dummy data would take it to the next level! Great job!

**Review by EmmS21 — APPROVED** [review]
Great job everyone, code in component looks well structured and overall very readable

**Review by laurensruiz — APPROVED** [review]
The basic design looks really good and structured well. The code looks very clean as well. The functionality is great but instead of hardcoding the data, I suggest working with dummyData to implement a more accessible code.

**Pull request merged**
