### PR TITLE
Feature/login form

### PR DESCRIPTION
**Pull request by kfam22**
## Description

**Description:** Implemented the new login page design with CSS and HTML Ensured that the login page is responsive.

Screen Shot 2022-04-20 at 11 56 25 AM

## Loom Video

[Video](https://www.loom.com/share/ab74ef3cbcb743d28ebfdab1f21ee016) walkthrough 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Divici — APPROVED** [review]
You did a really good job with the clean and responsive design. It doesn't look like there is any unnecessary code in your .js files and I don't see a way that you could have efficiently combined any of the CSS styles, so well done.

**Review by Adamh1990 — APPROVED** [review]
Clean code that looks really good, I can't see anything to complain about, well done!

**Review by brandon-bee — APPROVED** [review]
Really good stuff here! You did a great job matching all the standards and conventions in place, and as usual you are a styling wizard! Each page looks very clean.

**Comment by ivanovicuros** [comment]
Really good job on responsiveness! Design looks great!

**Review by ElchinNasirov — APPROVED** [review]

**Pull request merged**
