### PR TITLE
BL-304 Bug/footer contact

### PR DESCRIPTION
**Pull request by kevkenshi-max**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by kevkenshi-max** [comment]
https://www.loom.com/share/5637379d1b70424089c6cfe1677822b7

**Comment by kevkenshi-max** [comment]
Implemented the functionality on contact information to navigate to the email account when clicked.

**Comment by Benroberts37** [comment]
Hey Kevin, I submitted a pull request for this same thing on Wednesday (https://github.com/BloomTech-Labs/coder-heroes-fe/pull/255)

Was curious if there is any advantages to the way you formatted the code vs. the way I had it (<a href="mailto:brianne@coderheroes.com")

Thanks and let me know what you think. After talking to Edd, he mentioned generally the first pull request submitted is the one we would merge, but since we approached this slightly differently I wanted to check with you what you think the best approach is.

**Comment by kevkenshi-max** [comment]
Hello, Ben.
Yeah. I've realized that there is a conflict with this pull request...
I guess we could ignore my PR. Thanks for letting me know.
I'm not sure what to do when there is a conflict like that in Github. Do I
cancel or anything? or do I simply ignore it?
Thanks

**Comment by Benroberts37** [comment]
Hey Kevin, not 100% sure. There is this article that explains it a bit. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

If I understand it correctly, you need to edit the code on your local machine and then delete the pull request? I honestly haven't run into this yet. 

I will also add you to the Trello ticket so that maybe you can also get credit for this in terms of points, even if you delete this pull request.

**Comment by kevkenshi-max** [comment]
Awesome, thanks!

**Review by ivanovicuros — APPROVED** [review]

**Review by bezzantsam — APPROVED** [review]
Good fix, it is surprising that wasn't a priority function since it i live and active. Only thing I would suggest is get someone on the ticket with you in the future and spread the story point love around.

**Review by kylerostler — APPROVED** [review]
Great job cleaning the contact area up and making the links more intuitive and actually link to sending and email or contacting someone.

**Review by spencerlonghurst — APPROVED** [review]
Looks good! I am not sure if this one will be used or if the one Ben made will be used, but I love the little details and it all looks good!

**Pull request merged**
