### PR TITLE
alphabetized the state order

### PR DESCRIPTION
**Pull request by seanmp3**
## Description
Quick fix getting the state list to be in alphabetical order.

https://www.loom.com/share/317912638e104967bdf31fd745aa979d

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by mark-escosura — APPROVED** [review]

**Review by mcmillanj — APPROVED** [review]
approved

**Review by waylonturbes — COMMENTED** [review]
Would be better to convert this array of states into an object? It would allow us to grab states by their key name rather than their index.

**Comment by seanmp3** [comment]
> Would it be better to convert this array of states into an object? It would allow us to grab states by their key name rather than their index.

Possibly, I think we should wait to actually do that until we're using the data somewhere; you never know why something is what it is until you see it in the big picture, but that sounds like a good idea with me not fully knowing the context.

**Review by waylonturbes — APPROVED** [review]
These changes look like they have corrected the alphabetical order of US states. Good job.

**Review by manny-glez — APPROVED** [review]
Good catch, looks great.

**Review by mcmillanj — APPROVED** [review]
Nice

**Pull request merged**
