### PR TITLE
Fix/readme

### PR DESCRIPTION
**Pull request by ModupeD**
## Description

I added updated contributors to the readme.
Fixes # (issue)

## Loom Video

https://www.loom.com/share/279514ec78574af1baa2c6b53c439472

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by krisf451 — APPROVED** [review]
Small, but needed change. Thankyou Mo!

**Review by ElchinNasirov — APPROVED** [review]

**Review by 19jlevitre — APPROVED** [review]
Looks like a good and helpful change! thanks for being detail oriented!

**Comment by PriscilaMonteiro** [comment]
Thank you for doing that Mo! Nice move.

**Review by natecheney-dev — APPROVED** [review]
Great job, the changes/concerns I brought up were addressed and fixed, thanks!

**Review by waylonturbes — APPROVED** [review]
Nice job updating the README's contributors section and removing those Loom videos. Some of them were broken (404), and this project has moved too far for those videos to be of much use.

**Pull request merged**
