### PR TITLE
BL 736 cleanup for add programs course components

### PR DESCRIPTION
**Pull request by laurensruiz**
## Description
Cleaned up Add Programs/Course coponents, noticed components have 3 different names via import through another component (e.g. The export default is AddCourse but the import is renamed AddProgram). Changed all "Programs" within file names and functions to "Courses" to reflect what the component is actually needed for.

Fixes # (BL-736)

## Loom Video
(https://www.loom.com/share/33ca4f97e0334366903f07004936d7eb)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Rlauckern — APPROVED** [review]
Good job cleaning up and making them consistent.

**Review by EmmS21 — APPROVED** [review]
Great clean up, makes the codebase a lot easier to read and understand

**Review by tkordysh — DISMISSED** [review]
Thanks for taking care of this. Now that there is more clarity on the program/course/class relationship it will be important to go through the existing codebase and UX designs to check for consistency as you did here. Nice job!

**Review by Irving-Delgad0 — APPROVED** [review]
Nice job catching these bugs! its definitely essential to keep things clean and consistent

**Pull request merged**
