### PR TITLE
Family page designed **not done working on state/etc.

### PR DESCRIPTION
**Pull request by nforman91**
## Description

I designed a Family page where, as a parent, eventually one could add, change, or delete students on the account. I first designed the page on Figma, then implemented the page based on the design. I edited the following files: 

- src/components/pages/ParentFamily - I added this folder to hold the ParentFamilyHome component.

- src/components/common/Banner.js - I added the path so that the correct title is displayed in the banner.

- src/components/pages/ParentFamily/ParentFamilyHome.js - This is the component that most of the work was done in.  I imported the Banner and ParentSidebar to keep formatting consistent between the dashboard and this page. There is no state functionality in this component (if anyone is able to help implement this, please let me know), I only have the styling done as of now.

- src/index.js - I imported my new ParentFamilyHome component and created a new route for it.

- src/styles/ParentStyles/index.less - I added the styling for the FamilyPage to the bottom of this .less file.

[Trello card link](https://trello.com/c/MzXpqW47)
[Loom video](https://www.loom.com/share/11157d54d6ff45dcbdf4ffa3998bcaf0)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by alextcedwards — APPROVED** [review]
informative video, the styles look good! thanks

**Review by ElchinNasirov — APPROVED** [review]
The design looks good to me. Well done!

**Review by RoseGabriely — APPROVED** [review]
I am confused about the last commit "syncs package-lock".

Looks good otherwise!

**Review by JesusNavarrete215 — APPROVED** [review]
The design looks great!

**Comment by nforman91** [comment]
> I am confused about the last commit "syncs package-lock".
> 
> Looks good otherwise!

I had merge conflicts with the package-lock.json. So, I had to copy the code from the repo & replace the code in my local version with that code. Then I made the 'sync package-lock' commit & there were no merge conflicts.

**Pull request merged**
