### PR TITLE
Bl 827 fe i want to administer courses

### PR DESCRIPTION
**Pull request by reneetro**
## Description

Designed and implemented an "Edit Course Details" page for an admin user. Created a stylesheet specifically for the AdminEditCourseForm, and created a route to the page in the src/index.js file. Form currently populates with data from dummyData.

Fixes # (issue)

## Loom Video

https://loom.com/share/702e9dbfd33a4643a00b7ff56c8ac385

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have removed unnecessary comments/console logs from my code
- [ x] I have made corresponding changes to the documentation if necessary (optional)
- [ x] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings
- [ x] No duplicate code left within changed files
- [ x] Size of pull request kept to a minimum
- [ x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by techlando — APPROVED** [review]
Well organized and implemented. Also like the comments

**Review by dshipuk — DISMISSED** [review]
Code looks great! don't see any issues. Overall great job!

**Comment by gclancy121** [comment]
Looks good to me, I don't see any issues

**Review by lisamdespain — DISMISSED** [review]
This looks really good. I haven't seen Ant forms used before - it's good to know it has so many features (date picker, input number, checkbox). Also worth mentioning all the css you wrote to make it compliant with the stakeholder's UX. I'm super-impressed that you were able to adjust the width of that date picker, too!

**Pull request merged**
