### PR TITLE
 changed page routing so that the landing page renders first

### PR DESCRIPTION
**Pull request by 19jlevitre**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
When the page loaded you saw the sign up page first. This change makes it so the landing page is displayed first.

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .
https://www.loom.com/share/4d454d7a18cb453f98177f8d85c61ae8
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by krisf451 — APPROVED** [review]
A quick, but needed change. Good work.

**Review by Cheyenneb96 — APPROVED** [review]

**Review by waylonturbes — APPROVED** [review]
Good job! Now the app will direct users to the landing page rather than login.

**Review by seanmp3 — APPROVED** [review]
Looks good man, its gonna be exciting opening to that beautiful landing page

**Review by mark-escosura — APPROVED** [review]

**Review by manny-glez — APPROVED** [review]
Great work, now the landing page is living up to it's name.

**Review by ElchinNasirov — APPROVED** [review]

**Comment by ModupeD** [comment]
This change was very important, the first thing the user should see is the landing page. Awesome job

**Pull request merged**
