### PR TITLE
Landing Page Responsiveness

### PR DESCRIPTION
**Pull request by bugsbrog**
## Description

Enabling responsiveness on RenderLandPaging component by enabling media queries for desktop, tablet, and mobile devices. In addition, we are fixing the alignment of the footer component.

Co-authored-by: [peterdavidconley](https://github.com/peterdavidconley) <[peter.david.conley@gmail.com](mailto:peter.david.conley@gmail.com)>
Co-authored-by: [bugsbrog](https://github.com/bugsbrog) <[bugsbrog@gmail.com](mailto:bugsbrog@gmail.com)>

Fixes # (issue)

## Loom Video

[Loom Video](https://www.loom.com/share/12c0f459942a4adaa8219642ae3167b3)
<a href="https://www.loom.com/share/12c0f459942a4adaa8219642ae3167b3">
    <p>Library | Loom - 22 April 2022 - Watch Video</p>
    
  </a>

[Hannah's Loom Video](https://www.loom.com/share/2a6be21981d9410ab0f17bab14baaee3)
<a href="https://www.loom.com/share/2a6be21981d9410ab0f17bab14baaee3">
    <p>Library | Loom - 22 April 2022 - Watch Video</p>
    
  </a>

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by nyamekyeannor — APPROVED** [review]
Hannah and Peter this is amazing work. The landing page really needed some work on the responsive side and I think you were able to tackle it one step at a time.

I see the changes you made with compiling the CSS files for each individual component. That was a nice Idea not only for clean code and orderliness but it took it out of its global compilation state. 

Also, I'm a big fan of the way you structured your CSS; Making it easy to locate the section worked on.  There's not much I can say about the responsiveness. I see that you did an amazing job using media Quires to adjust the screen width. I would have loved to see you drop down the hamburger menu to show us how you embedded the navbar into it but besides that amazing job Hannah and Peter.

**Review by dconley1212 — APPROVED** [review]
The css changes look great! Nice work Peter!

**Review by sharontsanchez — APPROVED** [review]
Great job hannah and peter!!! I have been eagerly waiting for this and I love all the effective changes made to this landing page. The time you took to go through each line of code, and separate the styling for landing page from the parent page is detailed. I personally also like that the breakpoints are labelled to easily follow through.

**Comment by peterdavidconley** [comment]
> Hannah and Peter this is amazing work. The landing page really needed some work on the responsive side and I think you were able to tackle it one step at a time.
> 
> I see the changes you made with compiling the CSS files for each individual component. That was a nice Idea not only for clean code and orderliness but it took it out of its global compilation state.
> 
> Also, I'm a big fan of the way you structured your CSS; Making it easy to locate the section worked on. There's not much I can say about the responsiveness. I see that you did an amazing job using media Quires to adjust the screen width. I would have loved to see you drop down the hamburger menu to show us how you embedded the navbar into it but besides that amazing job Hannah and Peter.

Deeply appreciate the feedback.

**Review by joeys1122 — APPROVED** [review]
Nice work Peter and Hannah, the only thing I'd suggest is refactoring the code into antd components so you can make things more clean and compact, but otherwise the styling itself looks great! Keep up the good work.

**Pull request merged**
