### PR TITLE
Feature/adminhome

### PR DESCRIPTION
**Pull request by MarkTrepanier**
## Description

Added Admin and SuperAdmin home folders. They are duplicated from the Instructor's home folders. There are minor differences between them. The calendar is still attached to the instructor dummy data. The Tabs are non-functional.
There are no routes as of yet that lead to the pages.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes
https://www.loom.com/share/9f2775d4bac64ebc91e01db17a2a2abf

### CODE REVIEW

**Review by RoseGabriely — APPROVED** [review]
Looks like a good skeleton for these accounts if we choose to move forward with creating them!

**Review by ElchinNasirov — APPROVED** [review]
Everything looks good and the video was helpful.

**Review by alextcedwards — APPROVED** [review]
Like the video, looks good

**Review by JesusNavarrete215 — APPROVED** [review]
Hey mark, it looks good. Reviewing your code, nothing popped at me to improve on. Overall nice structure.

**Pull request merged**
