### PR TITLE
Modified src/components/common/Banner.js Component so that it's more DRY and reusable

### PR DESCRIPTION
**Pull request by vannguyen141290**
I made changes in Banner so that it can be usable and DRY.
Loom [https://www.loom.com/share/c9c0af1e51114141a3f7771adc531a10](url)

### CODE REVIEW

**Review by huiminzhang0111 — APPROVED** [review]
This is nice! the Banner now is more flexible and readable!

**Review by Pauline122112 — COMMENTED** [review]
Excellent work! I'm still concerned that the eslint warnings are still appearing, but still, content is clean and reusable.

**Comment by vannguyen141290** [comment]
> Excellent work! I'm still concerned that the eslint warnings are still appearing, but still, content is clean and reusable.

Yeah I know. but Ash said he would take care of eslinst so I think when it gets merged with main, it will be fine

**Review by Pauline122112 — APPROVED** [review]

**Review by TraNequaFauntleroy — COMMENTED** [review]
I love how you refactored the banner function to be more legible and more reusable. Great job!

**Pull request merged**
