### PR TITLE
Bug/parent sidebarnav cleanup

### PR DESCRIPTION
**Pull request by dstrazzeri**
## Description

Altered sidebar nav for the parent flow. There were multiple links that were unnecessary, as well as mismatched icons, change of some link names to be more relevant and some styling changes.

Fixes # (issue)

- Removed duplicate cart link & unnecessary links such as Logout and Dashboard
- Changed Icons to all be matching
- Changed link names to be more relevant such as "My Courses" to "Courses"
- Implemented Flexbox so links were not all at the top of sidenav

## Loom Video (Encountered more issues on other files while going through my changes)
https://www.loom.com/share/62da89c3bbce4acc9072dfd868d858dd

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by rjgeng — APPROVED** [review]
The all messed things have been cleared and sorted. The sidebarnav has a more meaningful logic in my view. A great job to save the following teammate tasks!

**Review by WRWPhillips — APPROVED** [review]
Much much cleaner and prettier, and I love react-icons! The changes to the items make more sense, and the icons look more consistent. Overall a great piece of design alignment, makes the component more usable and pleasant. These little things all add up!

**Review by Sug4rSku11 — APPROVED** [review]
Great job removing unnecessary links from the side navbar and making all of the icons the same style. Looks much better.

**Review by kevkenshi-max — COMMENTED** [review]
Two cart routes are indeed unnecessary. The parent sidebarnav looks cleaner now.

**Review by kevkenshi-max — APPROVED** [review]

**Review by ElchinNasirov — APPROVED** [review]

**Pull request merged**
