### PR TITLE
deleted unnecessary README in other directories and organized them in…

### PR DESCRIPTION
**Pull request by vannguyen141290**
This is task 1-4 in Trello >> Progress >> Documentation for front-end (README).
Basically there are multiple README.md in the whole repo, so I re-organized them into one single README in the root directory and deleted other README so that other developers are not too confused.

Also, I added another commit to use eslint-disable-next-line for un-used variables in case we need it in the future, along with determine alt for image tags in AvailableCourses.js so that it won't show errors.

loom
[https://www.loom.com/share/1082daf8eadf47ea82559e9ab39ec66e](url)
[https://www.loom.com/share/e72d1c23397348beb33b4be620d80c47](url)

### CODE REVIEW

**Review by ehsan2793 — COMMENTED** [review]
Very nice, very clean; instead of multiple read me files now, we only have 1.

the only issue I see is some other files like src/__tests__/RenderHomePage.test.js were also sent up

**Review by Pauline122112 — COMMENTED** [review]
Very clean, well done! In regards to why the PR is showing the "Unchanged files with check annotations". I'm unsure as to how they came to be on this PR. However, it seems to be a eslint issue (18 warnings to be exact after running npm run lint locally) Something that I will discuss further with the other TPM's and Ash, at the moment, it's an annoyance, but if we want to maintain a clean working environment, then this will need to be addressed. But overall, good job!

**Review by stevenjhomem — CHANGES_REQUESTED** [review]
Thanks for deleting these extra readme files!

I think I will request changes though so that we can disable the eslinting errors on the other errors here on the bottom of the page.
Screen Shot 2021-12-06 at 10 12 38 AM
e.

**Review by Brendonjhawkins — CHANGES_REQUESTED** [review]
Great Work Thi.

There are some additional Lint errors; requesting changes for those be removed as well.

**Review by TraNequaFauntleroy — COMMENTED** [review]
Great job cleaning up the extra README files. 

I also noticed that you disabled some unused variables.  

Good eye on lines 24, 28 and 35 of the AvailableCourses component. I see you caught the "==" vs "===" error.

**Review by TraNequaFauntleroy — CHANGES_REQUESTED** [review]
One question, what is the purpose of the notes in RenderDataViz file (lines 6-11)? I thought we did not have DS people on our team. Are those notes necessary?

**Review by Brendonjhawkins — APPROVED** [review]

**Review by stevenjhomem — APPROVED** [review]

**Comment by cqian12** [comment]
The hook dependency linting issue has actually been resolved as well, excuse my titling for the commit. One thing to note - I resolved capitalization issues in AvailableCourses that were leading to spellcheck suggestions: SetcurrentTab is now SetCurrentTab and Datetoday is now DateToday

**Comment by vannguyen141290** [comment]
> One question, what is the purpose of the notes in RenderDataViz file (lines 6-11)? I thought we did not have DS people on our team. Are those notes necessary?

I'm not sure, but maybe when we go further, we might need DS to do certain stuff, and it's just for reference, so I think it's ok to leave it there.

**Pull request merged**
