### PR TITLE
Bl 581 sidebar cart now reflects added courses

### PR DESCRIPTION
**Pull request by Rebecca-Stone**
## Description

the sidebar cart component was previously not rendering the number of courses being added. With these changes, it now renders the correct number. 

https://bloomtechlabs.atlassian.net/browse/BL-581?atlOrigin=eyJpIjoiOGNmMGMyNGQ5OTgyNGFkMmI2OWJlODEwNWRkOTIzODIiLCJwIjoiaiJ9

## Loom Video

https://www.loom.com/share/5d8877a2bb334a698f80c1230083b08a

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by EmmS21 — APPROVED** [review]
Simple fix, but a necessary fix to ensure the cart is updated when a course is added

**Review by Michael-Subbarao — APPROVED** [review]
Great work here. The fix is clean and the loom video is very concise and helpful.

**Comment by laurensruiz** [comment]
Great fix and very necessary for the site. The code looks clean and well thought of.

**Review by laurensruiz — APPROVED** [review]
Great fix and very necessary for the site. The code looks clean and well thought of.

**Pull request merged**
