### PR TITLE
Bug-Fix: deleted extra line of code causing local host to show error instead of load

### PR DESCRIPTION
**Pull request by JessWillCode**
## Description

There was an extra line of code causing the local host to throw an error. I deleted that line of code because parent-2 was a duplicate.

Fixes # (issue)

## Loom Video

[Please paste a link here of a quick loom video walking through what you did in your PR .](https://www.loom.com/share/a1ecb0f597ef4c14b5079b0c401b9658)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ivanovicuros — APPROVED** [review]

**Review by JorgeEvangelista500 — APPROVED** [review]
Thank you for fixing this

**Review by nyamekyeannor — APPROVED** [review]
Thank you for this bug fix Jess!

**Review by magoha01 — APPROVED** [review]
Good catch! Way to keep an eye out for duplicate/ unused paths and simplify the codebase!

**Review by dbvker — APPROVED** [review]
Good fix!

**Review by EduarddoEscobar — APPROVED** [review]
Good find!

**Review by brandon-bee — APPROVED** [review]
Nice catch!

**Review by peterdavidconley — APPROVED** [review]
Great catch and thanks for prioritizing this so that it didn't cause compiling errors when others cloned down the most current branch of main. Great job!

**Review by bugsbrog — APPROVED** [review]
Great job on cleaning your code up! Also good job on getting rid of the duplicate <Route>!

**Comment by ivanovicuros** [comment]
Good catch!

**Review by lizzythomson — APPROVED** [review]
Nice catch! Looks great!

**Comment by brandib222** [comment]
Much needed fix! Everyone was commenting it out and Jess took the initiative to remove it.

**Pull request merged**
