### PR TITLE
Form for making a Newsfeed ----not Final

### PR DESCRIPTION
**Pull request by pjaepole**
## Description
- trello
https://trello.com/c/8uEbvOoz/124-as-an-instructor-i-can-post-newsfeed-articles-to-provide-relevant-resources-to-students
- NOT FINALIZED
- only making pull request so I can share the progress with the team

created barebone form using ant design, no styling is added here
I need some design direction to implement color layout and style.

onfinish(onsubmit) function is made, I just need the endpoint that I can send the post request to.

On successful post request, I set the useHistory using react-router-dom
so we can redirect users to page that we set to
and I need input from others on where to redirect users to

1/19/2022
- redirect the user (instructor) to the instructor main page on successful post request, 
- added classNames and added styles for elements in components

1/20/2022
- created another form for editing newsfeed

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Ryan-E-Mark — COMMENTED** [review]
Looking great so far!

As far as rerouting after the form is submitted, I think redirecting back to the instructor dashboard would be fine. We can also come back to this as the newsfeed is built out and we have a better understanding of how things are structured. 

the endpoint to send the post request will be: https://coder-heroes-api.herokuapp.com/newsfeed

**Comment by pjaepole** [comment]
Thank you for checking in Ryan, I will finish working on

**Review by nforman91 — COMMENTED** [review]
Looks great! I provided a UX design on Figma [here](https://www.figma.com/file/VoV0f8wvr8t3GDz8q4ffU7/Main?node-id=1113%3A1448) for the Newsfeed, please let me know if you have any feedback/want a walkthrough.

**Review by Ryan-E-Mark — APPROVED** [review]

**Review by RoseGabriely — COMMENTED** [review]
Make sure the linter is working properly! Looks like you may be missing a semicolon somewhere.

**Pull request closed without merging**
